PROGRAM: TOPLEVEL;

TOPLEVEL: FUNCTIONDECLARATION
        | FUNCTIONDEFINITION
        | TYPEDEFINITION;

STATEMENT: VARIABLEDECLARATION semicolon
         | RETURNSTATEMENT semicolon
         | EXPRESSIONSTATEMENT semicolon
         | IFSTATEMENT
         | BLOCK;

IFSTATEMENT: ifkeyword EXPRESSION STATEMENT;
FUNCTIONDECLARATION: ID PARAMETERLIST returnarrow TYPE;
FUNCTIONDEFINITION: ID PARAMETERLIST assignment BLOCK;
FUNCTIONCALL: ID ARGUMENTLIST;
VARIABLEDECLARATION: TYPE ID assignment EXPRESSION;
RETURNSTATEMENT: returnkeyword EXPRESSION;

TYPEDEFINITION: newtype ID equals PARAMETERLIST;

ARGUMENTLIST: parenopen EXPRESSION parenclose;

PARAMETERLIST: parenopen TYPEDVALUE parenclose
             | parenopen parenclose
             ;

EXPRESSIONSTATEMENT: EXPRESSION;

BLOCK: curlopen STATEMENT curlclose;

TYPEDVALUE: TYPE ID;
TYPE: ID;
ID: id;
LITERAL : intliteral
        | stringliteral;

BINOP : equals
      | lessthan
      | plus
      | minus
      | mul
      | greaterthan;

EXPRESSION: ID
          | LITERAL
          | parenopen EXPRESSION parenclose
          | EXPRESSION BINOP EXPRESSION
          | FUNCTIONCALL;
